### ISSUE TITLE
Patient archiving broken

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#2423]
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**

Patient archiving appears to be in an unworkable state -

```
rails db:drop db:create db:migrate db:seed
rails c
ArchivedPatient.archive_eligible_patients!
```

result looks like it's an error on `can_fulfill_id` not being set, but it's not totally clear why:
```
/Users/colin/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `exec_params': PG::NotNullViolation: ERROR:  null value in column "can_fulfill_id" of relation "fulfillments" violates not-null constraint (ActiveRecord::NotNullViolation)
DETAIL:  Failing row contains (79, f, null, null, null, null, null, null, ArchivedPatient, null, 2021-11-07 18:22:31.516136, 2021-11-07 18:22:31.516136, 1).
/Users/colin/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `exec_params': ERROR:  null value in column "can_fulfill_id" of relation "fulfillments" violates not-null constraint (PG::NotNullViolation)
DETAIL:  Failing row contains (79, f, null, null, null, null, null, null, ArchivedPatient, null, 2021-11-07 18:22:31.516136, 2021-11-07 18:22:31.516136, 1).
```

* **What feature or behavior is this required for?**

Patient archiving (considered a safety feature, so we should get this taken care of soon)

* **How could we solve this issue? (Not knowing is okay!)**

I'm not totally sure. I would bet that this is running headlong into the `validates_associated :fulfillment` for some reason. THe place I would start is setting current tenant in this block. 

* **Anything else?**
nah

**Comment by colinxfleming** [comment]
@DarthHater tagging you in
